### ISSUE TITLE
Sample is not changed in the  spectral_init function

### ISSUE THREAD

**Issue by Kharitok** [laboGigan/ptychography-spectral#1]
Hello!

My name Is Konstantin and I am a PD student at DESY FLASH working on automatic-differentiation-powered Ptychography.

I've read your paper and wanted to try to utilize the spectral initialization of the sample to see if it will improve my reconstructions.
I've tried your code for `spectral_init` on the synthetic example of the far-field ptychography.
I kinda implemented the `propagate` myself by applying of  forward and backward far field propagator in 

https://github.com/laboGigan/ptychography-spectral/blob/01d6a48272226db2f719b1d4dfd8c2d7eaa6843e/Ptychography_with_spectral_init.py#L36
and 

https://github.com/laboGigan/ptychography-spectral/blob/01d6a48272226db2f719b1d4dfd8c2d7eaa6843e/Ptychography_with_spectral_init.py#L57-L58

But the code doses nothing for me, since, if I understand it correctly it only applies normalization to the initial object assumption by the lines 

https://github.com/laboGigan/ptychography-spectral/blob/01d6a48272226db2f719b1d4dfd8c2d7eaa6843e/Ptychography_with_spectral_init.py#L24

and

https://github.com/laboGigan/ptychography-spectral/blob/01d6a48272226db2f719b1d4dfd8c2d7eaa6843e/Ptychography_with_spectral_init.py#L60

Shouldn't it be  the `sol = v`  added before the line 60, or am I wrong?

**Comment by valzanialorenzo** [comment]
Hello Konstantin,
Thank you for spotting the missing line.
Precisely, your suggestion is correct and the code has been modified accordingly.
Cheers!
